{{- if and .Values.redisCluster.enabled }}
apiVersion: db.payu.com/v1
kind: RedisCluster
metadata:
  name: {{ .Values.redisCluster.name }}
  namespace: {{ .Values.redisCluster.namespace }}
spec:
{{- if .Values.redisCluster.leaderCount }}
  leaderCount: {{ .Values.redisCluster.leaderCount }}
{{- end }}
{{- if .Values.redisCluster.leaderFollowersCount }}
  leaderFollowersCount: {{ .Values.redisCluster.leaderFollowersCount }}
{{- end }}
  podLabelSelector: {{ toYaml .Values.redisCluster.podLabelSelector | nindent 4 }}
{{- if .Values.redisCluster.enableDefaultAffinity }}
  enableDefaultAffinity: {{ .Values.redisCluster.enableDefaultAffinity }}
{{- end }}
{{- if .Values.redisCluster.annotations }}
  annotations: {{ toYaml .Values.redisCluster.annotations | nindent 4 }}
{{- end }}
{{- if .Values.redisCluster.labels }}
  annotations: {{ toYaml .Values.redisCluster.labels | nindent 4 }}
{{- end }}
  redisPodSpec: {{ toYaml .Values.redisCluster.redisPodSpec | nindent 4 }}
{{- end }}
