{{- if and .Values.redisCluster.enabled }}
apiVersion: db.payu.com/v1
kind: RedisCluster
metadata:
  name: {{ .Values.redisCluster.name }}
  namespace: {{ .Values.redisCluster.namespace }}
spec:
{{- if .Values.redisCluster.leaderCount }}
  leaderCount: {{ .Values.redisCluster.leaderCount }}
{{- end }}
{{- if .Values.redisCluster.leaderFollowersCount }}
  leaderFollowersCount: {{ .Values.redisCluster.leaderFollowersCount }}
{{- end }}
  redis: {{ toYaml .Values.redisCluster.redis | nindent 4 }}
{{- if .Values.redisCluster.initContainer }}
  initContainer: {{ toYaml .Values.redisCluster.initContainer | nindent 4 }}
{{- end }}
  podLabelSelector: {{ toYaml .Values.redisCluster.podLabelSelector | nindent 4 }}
{{- if .Values.redisCluster.prometheusExporter }}
  prometheusExporter: {{ toYaml .Values.redisCluster.prometheusExporter | nindent 4 }}
{{- end }}
{{- if .Values.redisCluster.imagePullSecrets }}
  imagePullSecrets: {{ .Values.redisCluster.imagePullSecrets }}
{{- end }}
{{- if .Values.redisCluster.podAnnotations }}
  podAnnotations: {{ toYaml .Values.redisCluster.podAnnotations | nindent 4 }}
{{- end }}
  affinity:
    hostTopologyKey: {{ .Values.redisCluster.hostTopologyKey }}
    zoneTopologyKey: {{ .Values.redisCluster.zoneTopologyKey }}
{{- if .Values.redisCluster.enableHugePages }}
  enableHugePages:  {{ .Values.redisCluster.enableHugePages }}
{{- end }}
{{- end }}
