apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-clusterrole
subjects:
- kind: ServiceAccount
  name: redis-operator-manager-serviceaccount
  namespace: default
