apiVersion: db.payu.com/v1
kind: RedisCluster
metadata:
  name: rdc-test
  namespace: default
spec:
  leaderCount: 3
  leaderFollowersCount: 2
  enableHugePages: false

  redis:
    name: redis-container
    image: redis:testing
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 50Mi
    env:
    - name: PORT
      value: '6379'
    - name: CONF_PATH
      value: '/usr/local/etc/redis/redis.conf'
    ports:
    - containerPort: 6379

  initContainer:
    name: redis-init-container
    image: redis-init:testing
    imagePullPolicy: IfNotPresent

  prometheusExporter:
    name: redis-metric-exporter
    image: metrics-exporter:testing
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 9121

  imagePullSecrets: "regcred"
  podLabelSelector:
    app: "redis"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  affinity:
    hostTopologyKey: "kubernetes.io/hostname"
    zoneTopologyKey: "failure-domain.beta.kubernetes.io/zone"
