apiVersion: db.payu.com/v1
kind: RedisCluster
metadata:
  name: rdc-test
  namespace: infra
spec:
  leaderCount: 3
  leaderFollowersCount: 2
  image: "redis:testing"
  initContainer:
    image: "redis-init:testing"
  imagePullSecrets: "regcred"
  redisContainerResources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 50Mi
  podLabelSelector:
    app: "redis"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  affinity:
    hostTopologyKey: "kubernetes.io/hostname"
    zoneTopologyKey: "failure-domain.beta.kubernetes.io/zone"
  redisContainerEnvVariables:
    - name: PORT
      value: '6379'
    - name: CONF_PATH
      value: '/usr/local/etc/redis/redis.conf'
