apiVersion: db.payu.com/v1
kind: RedisCluster
metadata:
  name: rdc-test
  namespace: default
spec:
  leaderCount: 3
  leaderFollowersCount: 1
  enableDefaultAffinity: true
  podLabelSelector:
    app: redis-cluster-pod

  redisPodSpec:
    containers:
    - name: redis-container
      image: redis:testing
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 2500Mi
        requests:
          cpu: 50m
          memory: 50Mi
      env:
      - name: PORT
        value: "6379"
      - name: CONF_PATH
        value: "/usr/local/etc/redis/redis.conf"
      ports:
      - containerPort: 6379
      volumeMounts:
      - name: redis-node-configuration
        mountPath: "/usr/local/etc/redis"

    - name: redis-metric-exporter
      image: metrics-exporter:testing
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 9121

    initContainers:
    - name: redis-init-container
      image: redis-init:testing
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
        runAsNonRoot: false
        runAsUser: 0
      volumeMounts:
      - name: host-sys
        mountPath: "/host-sys"
      command:
        - "/bin/sh"
      args:
      - "-c"
      - "install_packages systemd procps && sysctl -w net.core.somaxconn=1024"
      # - "&& echo never > /host-sys/kernel/mm/transparent_hugepage/enabled"
      # - "&& grep -q -F [never] /sys/kernel/mm/transparent_hugepage/enabled"

    volumes:
    - name: redis-node-configuration
      configMap:
        name: redis-node-settings-config-map
    - name: host-sys
      hostPath:
        path: "/sys"

    imagePullSecrets:
    - name: "regcred"

