{{- if .Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: "redis-operator"
rules:
- apiGroups:
  - db.payu.com
  resources:
  - redisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.payu.com
  resources:
  - redisclusters/status
  verbs:
  - get
  - patch
  - update
{{- end }}
