{{- if .Values.redisOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: {{ template "redis-operator.fullname" . }}-manager
  namespace: {{ .Values.redisOperator.namespace }}
spec:
  replicas: {{ .Values.redisOperator.managerReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations: {{ toYaml .Values.redisOperator.annotations | nindent 8 }}
      labels: {{ toYaml .Values.redisOperator.labels | nindent 8 }}
    spec:
      imagePullSecrets: {{ toYaml .Values.redisOperator.imagePullSecrets | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.redisOperator.terminationGracePeriodSeconds }}
      serviceAccountName: {{ .Values.redisOperator.serviceAccount.name }}
      containers: {{ toYaml .Values.redisOperator.containers | nindent 8 }}
{{- end }}
