generatorOptions:
  disableNameSuffixHash: true

configMapgenerator:
- name: redisconfig
  files:
    - ../configfiles/redis.conf
  options:
    labels:
      redis-cluster: dev-rdc
- name: users-acl
  files:
    - ../configfiles/users.acl
  options:
    labels:
      redis-cluster: dev-rdc
- name: operator-config
  files:
    - ../configfiles/operator.conf
  options:
    labels:
      redis-operator: dev-rdc
