{
 "title": "Redis cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(redis_up{pod_name=~\"redis-node.*\"}, env)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up{pod_name=~\"redis-node.*\", env=\"$env\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster topology",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(redis_instance_info{env=\"$env\", pod_name=~\"redis-node.*\"}) by (role)",
     "legendFormat": "{{ role }}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(redis_cluster_known_nodes{pod_name=~\"redis-node.*\",env=~\"$env\"}[5m])) by (env)"
    }
   ]
  },
  {
   "title": "Commands Executed / sec  ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total{env=~\"$env\", pod_name=~\"redis-node.*\"}[1m])) by (env)",
     "legendFormat": "Total Commands"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{env=\"$env\", pod_name=~\"redis-node.*\"})",
     "legendFormat": "Total Connected clients"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "irate(redis_cpu_sys_seconds_total{env=~\"$env\", pod_name=~\"redis-node.*\"}[1m]) * 10",
     "legendFormat": " {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage - Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{env=~\"$env\", pod_name=~\"redis-node.*\"} ",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage - Peak",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_peak_bytes{pod_name=~\"redis-node.*\",env=~\"$env\"} ",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_db_keys{env=~\"$env\", pod_name=~\"redis-node.*\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted Keys",
   "type": "graph",
   "description": "Expired or Evicted keys are keys deleted from Redis due to TTL (exp) or a certain memory level being reached (evc). TTL is set via the client during key creation; eviction is made to a set of keys randomly. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{pod_name=~\"redis-node.*\",env=~\"$env\"}[5m])) by (env)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{pod_name=~\"redis-node.*\",env=~\"$env\"}[5m])) by (env)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "description": "Keys found in cache (hits) and keys not found (misses)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_keyspace_hits_total{pod_name=~\"redis-node.*\", env=~\"$env\"}[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(irate(redis_keyspace_misses_total{pod_name=~\"redis-node.*\" ,env=~\"$env\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "description": "The cache hit ratio represents the efficiency of cache usage. If the cache hit ratio is lower than ~0.8 then a significant amount of the requested keys are evicted, expired, or do not exist at all.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_keyspace_hits_total{pod_name=~\"redis-node.*\", env=~\"$env\"}[5m])) / (sum(rate(redis_keyspace_hits_total{pod_name=~\"redis-node.*\", env=~\"$env\"}[5m])) + sum(rate(redis_keyspace_misses_total{pod_name=~\"redis-node.*\", env=~\"$env\"}[5m])))",
     "legendFormat": "Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "Node Rules",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_instance_info{env=\"$env\", pod_name=~\"redis-node.*\"}",
     "legendFormat": "{{ pod_name }} [{{ role }}]"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{pod_name=~\"redis-node.*\", env=~\"$env\"}[5m])) by (env)",
     "legendFormat": "Cluster uptime"
    }
   ]
  }
 ]
}