{
 "title": "Redis operator overview",
 "description": "Redis operator runtime metrics",
 "tags": [
  "golang",
  "redis"
 ],
 "time": { "from": "2021-02-10T10:58:01.812Z", "to": "2021-02-10T11:04:39.802Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(go_info{app=\"redis-operator-manager\"},namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(go_info{pod_name=~\".*\",app=\"redis-operator-manager\"},pod_name)"
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(go_info{env=~\".*\",app=\"redis-operator-manager\"},env)"
   }
  ]
 },
 "panels": [
  {
   "title": "REST client request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(rest_client_request_latency_seconds_bucket{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}[5m])) by (pod_name,verb,le))",
     "legendFormat": "{{verb}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "REST client request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}[1m])) by (code,method,pod_name)",
     "legendFormat": "{{method}}:{{code}}"
    }
   ]
  },
  {
   "title": "Reconcile loop duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{env=\"$env\",namespace=\"$namespace\",pod_name=~\"$pod\"}[10m])) by (le))",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_released_bytes"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_gc_sys_bytes"
    },
    {
     "expr": "go_memstats_next_gc_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_next_gc_bytes"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_sys_bytes"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_stack_sys_bytes"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}[1m])",
     "legendFormat": "go_memstats_mallocs_total"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "description": "Described as - 'The number of live objects is Mallocs - Frees' in: \nhttps://golang.org/pkg/runtime/",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"} - go_memstats_frees_total{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "live objects"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_goroutines"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}[1m])",
     "legendFormat": "go_memstats_lookups_total"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "go_gc_duration_seconds {{quantile}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app=\"redis-operator-manager\",namespace=\"$namespace\", pod_name=~\"$pod\"}[1m])",
     "legendFormat": "go_memstats_alloc_bytes_total"
    }
   ]
  }
 ]
}