apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: controller-manager
    redis-operator: rdc-test
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 2
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - command:
        - /manager
        image: controller:latest
        imagePullPolicy: "IfNotPresent"
        name: manager
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: REDIS_USERNAME
          value: "admin"
        - name: REDISCLI_AUTH
          value: "adminpass"
        - name: CLUSTER_VIEW_FILE
          value: "cluster_data"
        - name: CLUSTER_STATE_FILE
          value: "cluster_state"
        volumeMounts:
        - name: redis-operator-config
          mountPath: "/usr/local/etc/"
      terminationGracePeriodSeconds: 10
      serviceAccountName: "redis-operator-manager"
      volumes:
      - name: redis-operator-config
        configMap:
          name: redis-operator-operator-config
