apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 2
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - command:
        - /manager
        image: controller:latest
        imagePullPolicy: "IfNotPresent"
        name: manager
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 256Mi
      terminationGracePeriodSeconds: 10
      serviceAccountName: "redis-operator-manager"
